Fix problem of having reaction_id in template when generating dataset (#697)
open-reaction-database/ord-schema pull request #699
Opened 2023-08-25 02:13 UTC by FanwangM

2023-08-25 14:14 UTC, connorcoley requested changes
Instead of doing string operations on the template pbtxt, it would be cleaner to remove the field from the `dataset` after it is generated by the enumeration, I think. WDYT?

2023-08-28 15:52 UTC, FanwangM commented
> Instead of doing string operations on the template pbtxt, it would be cleaner to remove the field from the `dataset` after it is generated by the enumeration, I think. WDYT?

This can be a cleaner solution. New changes are committed here.

One question, do we need to assign a reaction_id for each reaction in the database after the reaction list is constructed?

2023-08-28 15:55 UTC, connorcoley commented
> One question, do we need to assign a reaction_id for each reaction in the database after the reaction list is constructed?

No, the submission workflows will automatically assign a `reaction_id` to each

2023-08-28 15:56 UTC, connorcoley approved these changes

2023-08-28 16:44 UTC, merged